export type Program={id:string;title:string;description:string;category:string;difficulty_level:string;estimated_duration_days:number|null;thumbnail_url?:string|null;tags?:string[]|null;total_lessons?:number};
export type MoodEntry={id?:string;user_id:string;mood_value:number;mood_label:string;energy_level?:number|null;anxiety_level?:number|null;stress_level?:number|null;sleep_hours?:number|null;sleep_quality?:number|null;notes?:string|null;entry_date:string};
export type AppSettings={id?:string;user_id:string;email_notifications:boolean;push_notifications:boolean;sms_notifications:boolean;appointment_reminders:boolean;ai_chat_notifications:boolean;profile_visibility:'public'|'therapists_only'|'private';data_sharing:boolean;analytics_opt_in:boolean;theme:'light'|'dark'|'auto';language:string;auto_save_chat:boolean};
export type UserProfile={id?:string;user_id:string;first_name:string;last_name:string;phone_number:string;profile_picture_url:string;bio:string;timezone:string;language_preference:string};
export type ChatMessage={id?:string;role:'user'|'assistant';content:string;created_at?:string};
export type TherapistProfile={first_name:string;last_name:string;license_number:string;license_state:string;specializations:string;years_experience:string;bio:string;phone_number:string;timezone:string;languages_spoken:string};
export type Therapist={user_id:string;first_name:string;last_name:string;license_state?:string|null;specializations?:string[]|null;degrees?:string[]|null;certifications?:string[]|null;years_experience?:number|null;bio?:string|null;profile_picture_url?:string|null;languages_spoken?:string[]|null;treatment_approaches?:string[]|null;age_groups_served?:string[]|null;rating:number;total_reviews:number;total_sessions:number;completed_sessions:number;is_verified:boolean;is_accepting_clients:boolean};
export type TherapistReview={id:string;rating:number;review_title?:string|null;review_text:string;created_at:string};
const API_BASE=import.meta.env.VITE_API_BASE_URL??'';const TOKEN_KEY='therafam:session';const USER_KEY='therafam:userId';
function headers(userId?:string,json=true){const h:Record<string,string>={};if(json)h['Content-Type']='application/json';const token=localStorage.getItem(TOKEN_KEY);if(token)h.Authorization=`Bearer ${token}`;else if(userId)h['X-Therafam-User-Id']=userId;return h}
async function api<T>(path:string,init:RequestInit={},userId?:string):Promise<T>{const r=await fetch(`${API_BASE}${path}`,{...init,headers:{...headers(userId),...(init.headers||{})}});const data=await r.json().catch(()=>null);if(!r.ok)throw new Error(data?.detail||data?.error||`Request failed with ${r.status}`);return data as T}
export function getStoredUserId(){return localStorage.getItem(USER_KEY)??''}export function getStoredToken(){return localStorage.getItem(TOKEN_KEY)??''}export function setSession(token:string,userId:string){localStorage.setItem(TOKEN_KEY,token);localStorage.setItem(USER_KEY,userId)}
export async function signOut(){try{await api('/api/auth/signout',{method:'POST'},getStoredUserId())}finally{localStorage.removeItem(TOKEN_KEY);localStorage.removeItem(USER_KEY)}}
export async function signIn(email:string,password:string){const r=await api<{user:{id:string};token:string}>('/api/auth/signin',{method:'POST',body:JSON.stringify({email,password})});setSession(r.token,r.user.id);return r}
export async function signUp(payload:Record<string,unknown>){const r=await api<{user:{id:string};token:string}>('/api/auth/signup',{method:'POST',body:JSON.stringify(payload)});setSession(r.token,r.user.id);return r}
export async function getHealth(){return api<{status:string;database_configured?:boolean}>('/api/health',{headers:{}})}
export async function sendAiMessage(message:string,history:ChatMessage[]=[],userId?:string){return api<{response:string;conversation_id?:string;crisis?:boolean;demo?:boolean}>('/api/chat',{method:'POST',body:JSON.stringify({message,history})},userId||getStoredUserId())}
export async function getPrograms(){return (await api<{programs:Program[]}>('/api/programs',{},getStoredUserId())).programs}export async function getLessons(programId:string){return (await api<{lessons:any[]}>('/api/programs/'+programId+'/lessons',{},getStoredUserId())).lessons}
export async function getMoodEntries(userId:string,limit=14){return (await api<{entries:MoodEntry[]}>(`/api/mood?limit=${limit}`,{},userId)).entries}export async function saveMoodEntry(entry:MoodEntry){return (await api<{entry:MoodEntry}>('/api/mood',{method:'POST',body:JSON.stringify(entry)},entry.user_id)).entry}
export async function getSettings(userId:string){return (await api<{settings:AppSettings|null}>('/api/settings',{},userId)).settings}export async function saveSettings(settings:AppSettings){return (await api<{settings:AppSettings}>('/api/settings',{method:'PUT',body:JSON.stringify(settings)},settings.user_id)).settings}
export async function getUserProfile(userId:string){return (await api<{profile:UserProfile|null}>('/api/profile',{},userId)).profile}export async function saveUserProfile(profile:UserProfile){return (await api<{profile:UserProfile}>('/api/profile',{method:'PUT',body:JSON.stringify(profile)},profile.user_id)).profile}
export async function uploadProfileImage(userId:string,file:File){if(!file.type.startsWith('image/'))throw new Error('Please select an image file.');if(file.size>5*1024*1024)throw new Error('Profile images must be 5 MB or smaller.');const form=new FormData();form.append('file',file);return (await api<{url:string}>('/api/profile/image',{method:'POST',headers:{},body:form},userId)).url}
export async function getTherapistDashboard(userId:string){return api<{profile:any;active_clients:number;upcoming_sessions:number}>('/api/therapist/dashboard',{},userId)}export async function getTherapistProfile(userId:string){return api<{profile:any}>('/api/therapist/profile',{},userId)}
export async function saveTherapistProfile(userId:string,profile:TherapistProfile){return api<{profile:any}>('/api/therapist/profile',{method:'PUT',body:JSON.stringify({...profile,specializations:profile.specializations.split(',').map(x=>x.trim()).filter(Boolean),languages_spoken:profile.languages_spoken.split(',').map(x=>x.trim()).filter(Boolean),years_experience:profile.years_experience?Number(profile.years_experience):null})},userId)}
export async function setTherapistAvailability(userId:string,is_accepting_clients:boolean){return api<{is_accepting_clients:boolean}>('/api/therapist/availability',{method:'PUT',body:JSON.stringify({is_accepting_clients})},userId)}export async function getTherapistClients(userId:string){return api<{clients:any[]}>('/api/therapist/clients',{},userId)}export async function getTherapistSessions(userId:string){return api<{sessions:any[]}>('/api/therapist/sessions',{},userId)}export async function getTherapistNotes(userId:string){return api<{notes:any[]}>('/api/therapist/notes',{},userId)}export async function getTherapistMessages(userId:string){return api<{messages:any[]}>('/api/therapist/messages',{},userId)}
export async function sendMessage(userId:string,recipientId:string,messageText:string,sessionId?:string){return api('/api/messages',{method:'POST',body:JSON.stringify({recipient_id:recipientId,message_text:messageText,session_id:sessionId})},userId)}export async function submitSupport(userId:string,category:'contact'|'report',message:string){return api<{submitted:boolean}>('/api/support',{method:'POST',body:JSON.stringify({category,message})},userId)}
export async function getTherapists(userId:string=getStoredUserId()){return (await api<{therapists:Therapist[]}>('/api/therapists',{},userId)).therapists}
export async function getTherapistReviews(therapistId:string,userId:string=getStoredUserId()){return (await api<{reviews:TherapistReview[]}>(`/api/therapists/${therapistId}/reviews`,{},userId)).reviews}
export async function getTherapistReviewStatus(therapistId:string,userId:string=getStoredUserId()){return api<{completed_sessions:number;required_sessions:number;eligible:boolean;already_reviewed:boolean}>(`/api/therapists/${therapistId}/review-status`,{},userId)}
export async function submitTherapistReview(userId:string,therapistId:string,rating:number,reviewText:string,reviewTitle?:string){return api<{submitted:boolean;review:TherapistReview}>('/api/therapists/reviews',{method:'POST',body:JSON.stringify({therapist_id:therapistId,rating,review_title:reviewTitle||null,review_text:reviewText})},userId)}
export type SubscriptionStatus={subscription:any;features_locked:boolean;trial_days_remaining:number|null};export type TherapistEarnings={available_balance:number;pending_balance:number;total_earned:number;total_withdrawn:number;performance:any;transactions:any[]};
export async function getSubscription(userId:string){return api<SubscriptionStatus>('/api/subscription',{},userId)}export async function upgradeSubscription(userId:string,plan:'premium_monthly'|'premium_annual'='premium_monthly'){return api('/api/subscription/upgrade',{method:'POST',body:JSON.stringify({plan})},userId)}export async function getTherapistEarnings(userId:string){return api<TherapistEarnings>('/api/therapist/earnings',{},userId)}export async function recalculateTherapistEarnings(userId:string){return api<{recalculated:boolean;new_earnings:number}>('/api/therapist/earnings/recalculate',{method:'POST'},userId)}export async function getTherapistPerformance(userId:string){return api<{performance_history:any[]}>('/api/therapist/performance',{},userId)}