import { useEffect, useState } from 'react';
import { createBooking, getTherapistAvailability, getTherapistById, Therapist } from '../lib/therafamApi';

type Props = { therapistId: string; onBack: () => void; onHome: () => void };
type Slot = { day_of_week:number; start_time:string; end_time:string; is_available:boolean };

export default function TherapistBooking({ therapistId, onBack, onHome }: Props) {
  const [therapist,setTherapist]=useState<Therapist|null>(null); const [slots,setSlots]=useState<Slot[]>([]); const [date,setDate]=useState(''); const [time,setTime]=useState(''); const [format,setFormat]=useState('video'); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [confirmed,setConfirmed]=useState(false);
  useEffect(()=>{Promise.all([getTherapistById(therapistId),getTherapistAvailability(therapistId)]).then(([p,a])=>{setTherapist(p);setSlots(a.slots||[])}).catch(e=>setError(e instanceof Error?e.message:'Unable to load therapist'))},[therapistId]);
  const availableSlots=slots.filter(s=>s.is_available);
  async function book(){setError('');if(!date||!time){setError('Choose a date and time for your session.');return}const start=new Date(`${date}T${time}`);const end=new Date(start.getTime()+50*60000);setBusy(true);try{await createBooking({therapist_id:therapistId,scheduled_start_time:start.toISOString(),scheduled_end_time:end.toISOString(),session_format:format as 'video'|'audio'|'in_person'|'chat'});setConfirmed(true)}catch(e){setError(e instanceof Error?e.message:'Booking failed')}finally{setBusy(false)}}
  if(confirmed)return <section className="booking-shell"><header className="workspace-topbar"><button className="workspace-brand" onClick={onHome}>Therafam</button></header><main className="booking-confirm"><div className="success-mark">✓</div><span className="eyebrow">Session requested</span><h1>Your session is booked</h1><p>Your appointment with {therapist?.first_name} {therapist?.last_name} has been added to your sessions.</p><button className="primary-action" onClick={onBack}>Back to therapist</button></main></section>;
  return <section className="booking-shell"><header className="workspace-topbar"><button className="workspace-brand" onClick={onHome}>Therafam</button><button className="text-link" onClick={onBack}>← Back</button></header><main className="booking-content"><div className="booking-profile"><div className="therapist-avatar">{therapist?.first_name?.[0]||'T'}</div><div><span className="eyebrow">Book a professional</span><h1>{therapist?`${therapist.first_name} ${therapist.last_name}`:'Loading…'}</h1><p>{therapist?.specializations?.join(' · ')||'Mental wellness professional'}</p><div>★ {(therapist?.rating??0).toFixed(1)} · {therapist?.total_reviews??0} reviews</div></div></div><div className="booking-grid"><article className="dashboard-card"><h2>Choose a session</h2><label>Date<input type="date" value={date} min={new Date().toISOString().slice(0,10)} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Session format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="video">Video</option><option value="audio">Audio</option><option value="chat">Chat</option><option value="in_person">In person</option></select></label>{availableSlots.length>0&&<p className="helper-copy">This professional has recurring availability configured. Choose a time within their listed working hours.</p>}<button className="primary-action full-action" disabled={busy||!therapist}>{busy?'Booking…':'Confirm booking'}</button>{error&&<div className="form-error">{error}</div>}</article><aside className="dashboard-card"><h2>Before your session</h2><p>Choose a quiet place and a time when you can participate comfortably.</p><p>Your appointment will appear in your sessions after confirmation.</p><p>You can use secure messaging if you need to communicate with your therapist.</p></aside></div></main></section>;
}
