import { useEffect, useState } from 'react';
import Brand from '../components/Brand';
import { supabase } from '../lib/supabase';
import { getStoredUserId } from '../lib/therafamApi';
import '../styles/therapist-portal.css';

type Props = { onBack: () => void; onHome: () => void };
type Panel = 'clients' | 'schedule' | 'profile' | 'notes' | 'availability' | 'messages' | null;
type Profile = { first_name:string; last_name:string; license_number:string; license_state:string; specializations:string; years_experience:string; bio:string; phone_number:string; timezone:string; languages_spoken:string };
const emptyProfile: Profile = {first_name:'',last_name:'',license_number:'',license_state:'',specializations:'',years_experience:'',bio:'',phone_number:'',timezone:'Africa/Lagos',languages_spoken:''};

export default function TherapistPortalInteractive({onBack,onHome}:Props){
 const [clientCount,setClientCount]=useState(0),[sessionCount,setSessionCount]=useState(0),[panel,setPanel]=useState<Panel>(null),[isActive,setIsActive]=useState(true),[savingStatus,setSavingStatus]=useState(false),[statusMessage,setStatusMessage]=useState('');
 const [profile,setProfile]=useState<Profile>(emptyProfile),[editing,setEditing]=useState(false),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const userId=getStoredUserId();
 useEffect(()=>{if(!supabase||!userId)return; Promise.all([
  supabase.from('therapist_client_relationships').select('id',{count:'exact',head:true}).eq('therapist_id',userId).eq('status','active'),
  supabase.from('therapy_sessions').select('id',{count:'exact',head:true}).eq('therapist_id',userId).eq('status','scheduled'),
  supabase.from('therapist_profiles').select('is_accepting_clients').eq('user_id',userId).maybeSingle()
 ]).then(([c,s,p])=>{setClientCount(c.count??0);setSessionCount(s.count??0);if(p.data?.is_accepting_clients!=null)setIsActive(Boolean(p.data.is_accepting_clients));});},[userId]);
 useEffect(()=>{if(supabase&&userId)return;const a=localStorage.getItem('therafam:therapist-active');if(a!==null)setIsActive(a==='true');const p=localStorage.getItem('therafam:therapist-profile');if(p)try{setProfile({...emptyProfile,...JSON.parse(p)})}catch{}},[userId]);
 async function openProfile(edit:boolean){setPanel('profile');setEditing(edit);setMessage('');setError('');if(!supabase||!userId)return;setLoading(true);const {data,error:e}=await supabase.from('therapist_profiles').select('first_name,last_name,license_number,license_state,specializations,years_experience,bio,phone_number,timezone,languages_spoken').eq('user_id',userId).maybeSingle();if(e)setError(e.message);if(data)setProfile({first_name:data.first_name??'',last_name:data.last_name??'',license_number:data.license_number??'',license_state:data.license_state??'',specializations:Array.isArray(data.specializations)?data.specializations.join(', '):'',years_experience:data.years_experience==null?'':String(data.years_experience),bio:data.bio??'',phone_number:data.phone_number??'',timezone:data.timezone??'Africa/Lagos',languages_spoken:Array.isArray(data.languages_spoken)?data.languages_spoken.join(', '):''});setLoading(false);}
 async function saveProfile(){setSaving(true);setMessage('');setError('');try{const payload={user_id:userId,first_name:profile.first_name.trim()||null,last_name:profile.last_name.trim()||null,license_number:profile.license_number.trim()||null,license_state:profile.license_state.trim()||null,specializations:list(profile.specializations),years_experience:profile.years_experience?Number(profile.years_experience):null,bio:profile.bio.trim()||null,phone_number:profile.phone_number.trim()||null,timezone:profile.timezone,languages_spoken:list(profile.languages_spoken),updated_at:new Date().toISOString()};if(supabase&&userId){const {error:e}=await supabase.from('therapist_profiles').upsert(payload,{onConflict:'user_id'});if(e)throw e;}else localStorage.setItem('therafam:therapist-profile',JSON.stringify(profile));setMessage('Profile saved successfully.');setEditing(false);}catch(e){setError(e instanceof Error?e.message:'Could not save your profile.');}finally{setSaving(false);}}
 async function toggleActive(){const next=!isActive;setIsActive(next);setSavingStatus(true);setStatusMessage('');try{if(supabase&&userId){const {error:e}=await supabase.from('therapist_profiles').update({is_accepting_clients:next,updated_at:new Date().toISOString()}).eq('user_id',userId);if(e)throw e;}else localStorage.setItem('therafam:therapist-active',String(next));setStatusMessage(next?'You are now accepting clients.':'You are now unavailable for new clients.');}catch(e){setIsActive(!next);setStatusMessage(e instanceof Error?e.message:'Could not update availability.');}finally{setSavingStatus(false);}}
 const close=()=>{setPanel(null);setEditing(false);setMessage('');setError('');};
 return <section className="workspace-shell therapist-workspace"><header className="workspace-topbar"><button className="workspace-brand" onClick={onHome} aria-label="Go home"><Brand compact/></button><div className="workspace-top-actions"><button className="text-link" onClick={onBack}>Return to client area</button><button className="avatar-button" onClick={()=>openProfile(false)} aria-label="Open professional profile">TF</button></div></header><div className="workspace-content">
  <div className="workspace-heading"><div><span className="eyebrow">Professional portal</span><h1>Therapist workspace</h1><p>Manage your client relationships, appointments, professional profile, and workflow securely.</p></div><div className="therapist-status-control"><span className={`status-dot ${isActive?'online':'offline'}`}/><div><strong>{isActive?'Active':'Offline'}</strong><small>{isActive?'Accepting new clients':'Not accepting new clients'}</small></div><button className={`status-toggle ${isActive?'on':'off'}`} onClick={toggleActive} disabled={savingStatus} aria-pressed={isActive} aria-label={isActive?'Set status offline':'Set status active'}><span/></button></div></div>
  {statusMessage&&<div className="status-feedback" role="status">{statusMessage}</div>}
  <div className="dashboard-grid"><Card label="Active clients" value={String(clientCount)} copy="Clients currently assigned to your care." action="View clients" onClick={()=>setPanel('clients')}/><Card label="Upcoming sessions" value={String(sessionCount)} copy="Scheduled sessions requiring attention." action="View schedule" onClick={()=>setPanel('schedule')}/><Card label="Professional profile" value={`${profile.first_name} ${profile.last_name}`.trim()||'Complete profile'} copy={profile.specializations||'Add your professional information and areas of practice.'} action="Edit profile" onClick={()=>openProfile(true)}/></div>
  <div className="therapist-columns"><section className="dashboard-card"><div className="card-heading"><strong>Today</strong><span>Schedule</span></div><div className="empty-state compact"><span>◷</span><strong>{sessionCount?`${sessionCount} scheduled session${sessionCount===1?'':'s'}`:'No sessions loaded'}</strong><p>{sessionCount?'Open your schedule to review appointment details.':'Your appointments will appear here when sessions are connected.'}</p><button className="outline-action" onClick={()=>setPanel('schedule')}>Open schedule</button></div></section><section className="dashboard-card"><div className="card-heading"><strong>Care workflow</strong><span>Secure</span></div><div className="workflow-list"><button onClick={()=>setPanel('notes')}>Review client notes <span>→</span></button><button onClick={()=>setPanel('availability')}>Update availability <span>→</span></button><button onClick={()=>setPanel('messages')}>Open secure messages <span>→</span></button></div></section></div>
  {panel&&<section className="settings-card therapist-action-panel"><div className="support-panel-header"><div><span className="eyebrow">Therapist workspace</span><h2>{title(panel)}</h2></div><button className="icon-action" onClick={close} aria-label="Close">×</button></div>{panel==='profile'?<ProfilePanel profile={profile} setProfile={setProfile} editing={editing} loading={loading} saving={saving} message={message} error={error} onEdit={()=>setEditing(true)} onSave={saveProfile} onCancel={()=>{setEditing(false);setMessage('');}} onClose={close}/>:<ActionPanel panel={panel} clientCount={clientCount} sessionCount={sessionCount} onClose={close} onRefresh={()=>window.location.reload()}/>}</section>}
 </div></section>;
}
function Card({label,value,copy:description,action,onClick}:{label:string;value:string;copy:string;action:string;onClick:()=>void}){return <article className="dashboard-card"><span className="eyebrow">{label}</span><strong className="workspace-stat">{value}</strong><p>{description}</p><button className="outline-action" onClick={onClick}>{action}</button></article>}
function ProfilePanel({profile,setProfile,editing,loading,saving,message,error,onEdit,onSave,onCancel,onClose}:{profile:Profile;setProfile:(p:Profile)=>void;editing:boolean;loading:boolean;saving:boolean;message:string;error:string;onEdit:()=>void;onSave:()=>void;onCancel:()=>void;onClose:()=>void}){const name=`${profile.first_name} ${profile.last_name}`.trim()||'Your professional profile';if(loading)return <div className="profile-loading">Loading professional profile…</div>;if(!editing)return <><div className="profile-summary"><div className="profile-avatar">{initials(name)}</div><div><h3>{name}</h3><p>{profile.specializations||'Specialization not added'}{profile.years_experience?` · ${profile.years_experience} years experience`:''}</p><p>{profile.license_number?`License: ${profile.license_number}`:'Professional license not added'}</p></div></div>{message&&<div className="profile-success">{message}</div>}{error&&<div className="profile-error">{error}</div>}<div className="profile-actions"><button className="primary-action" onClick={onEdit}>Edit professional information</button><button className="outline-action" onClick={onClose}>Close</button></div></>;return <div className="profile-form">
 <label>First name<input value={profile.first_name} onChange={e=>setProfile({...profile,first_name:e.target.value})}/></label><label>Last name<input value={profile.last_name} onChange={e=>setProfile({...profile,last_name:e.target.value})}/></label><label>Professional license number<input value={profile.license_number} onChange={e=>setProfile({...profile,license_number:e.target.value})}/></label><label>License state / region<input value={profile.license_state} onChange={e=>setProfile({...profile,license_state:e.target.value})}/></label><label>Specializations<input value={profile.specializations} onChange={e=>setProfile({...profile,specializations:e.target.value})} placeholder="CBT, family therapy"/></label><label>Years of experience<input type="number" min="0" max="70" value={profile.years_experience} onChange={e=>setProfile({...profile,years_experience:e.target.value})}/></label><label>Phone number<input value={profile.phone_number} onChange={e=>setProfile({...profile,phone_number:e.target.value})}/></label><label>Languages spoken<input value={profile.languages_spoken} onChange={e=>setProfile({...profile,languages_spoken:e.target.value})} placeholder="English, Hausa"/></label><label>Timezone<select value={profile.timezone} onChange={e=>setProfile({...profile,timezone:e.target.value})}><option>Africa/Lagos</option><option>UTC</option><option>Africa/Accra</option><option>Europe/London</option><option>America/New_York</option></select></label><label className="full">Professional bio<textarea maxLength={500} value={profile.bio} onChange={e=>setProfile({...profile,bio:e.target.value})} placeholder="Briefly describe your professional experience and approach."/></label>{error&&<div className="profile-error full">{error}</div>}{message&&<div className="profile-success full">{message}</div>}<div className="profile-edit-actions"><button className="outline-action" onClick={onCancel} disabled={saving}>Cancel</button><button className="primary-action" onClick={onSave} disabled={saving}>{saving?'Saving…':'Save profile'}</button></div></div>}
function ActionPanel({panel,clientCount,sessionCount,onClose,onRefresh}:{panel:Exclude<Panel,'profile'|null>;clientCount:number;sessionCount:number;onClose:()=>void;onRefresh:()=>void}){const copy=panel==='clients'?`${clientCount} active client${clientCount===1?'':'s'} currently assigned. Client details will appear here as authenticated relationship data is connected.`:panel==='schedule'?`${sessionCount} scheduled session${sessionCount===1?'':'s'} currently found. Appointment details will appear here as scheduling data is connected.`:panel==='notes'?'Client notes are protected by the authenticated therapist workflow. This panel is ready for secure notes integration.':panel==='availability'?'Use the Active switch above to control whether you accept new clients. Detailed weekly availability can be managed here next.':'Secure therapist-client messages will appear here when the authenticated messaging workflow is connected.';return <><p>{copy}</p><div className="profile-actions">{panel==='availability'&&<button className="primary-action" onClick={onClose}>Use Active switch</button>}<button className="outline-action" onClick={onRefresh}>Refresh data</button><button className="outline-action" onClick={onClose}>Close</button></div></>}
function list(v:string){return v.split(',').map(x=>x.trim()).filter(Boolean)}function initials(n:string){return n.split(' ').filter(Boolean).slice(0,2).map(x=>x[0].toUpperCase()).join('')||'TF'}function title(p:Panel){return p==='clients'?'Client relationships':p==='schedule'?'Session schedule':p==='profile'?'Professional profile':p==='notes'?'Client notes':p==='availability'?'Availability':'Secure messages'}
