/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tsyxilfagqbxhwijbaor"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzeXhpbGZhZ3FieGh3aWpiYW9yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIyMDcxNDAsImV4cCI6MjA3Nzc4MzE0MH0.0mSVumBxZmInI3BiNHgXwLnnR6o-jprASr6yKI3o560"
